// Generated by CoffeeScript 1.10.0
(function() {
  var _, app, delayTime, express, fs, qs, server, util, uuid;

  express = require('express');

  app = express();

  util = require('util');

  fs = require('fs-extra');

  qs = require('querystring');

  uuid = require('node-uuid');

  _ = require('lodash');

  delayTime = 0;

  app.all('/', function(req, res) {
    var data;
    data = 'hello';
    console.log(req);
    return res.send(req.headers);
  });

  server = app.listen(1113, function() {
    var host, port;
    host = server.address().address;
    port = server.address().port;
    return console.log('Example app listening at http://%s:%s', host, port);
  });

}).call(this);

//# sourceMappingURL=getheaduseexpress.js.map
