// Generated by CoffeeScript 1.10.0
(function() {
  var _, app, delayTime, express, fs, http, qs, server, url, util, uuid;

  express = require('express');

  app = express();

  util = require('util');

  fs = require('fs-extra');

  qs = require('querystring');

  uuid = require('node-uuid');

  _ = require('lodash');

  url = require('url');

  http = require('http');

  delayTime = 0;

  server = http.createServer(function(req, res) {
    var params;
    params = url.parse(req.url, true);
    console.log(req.headers);
    delayTime = 1000;
    switch (params.pathname) {
      case "/":
        return (function() {
          return setTimeout(function() {
            res.write('var http');
            return res.end(JSON.stringify(req.headers));
          }, delayTime);
        })();
      default:
        return (function() {
          var data;
          data = {
            "code": "404",
            "message": "连接未找到",
            "data": ""
          };
          return setTimeout(function() {
            if (params.query && params.query.callback) {
              res.write(params.query.callback + '(' + JSON.stringify(data) + ')');
            } else {
              res.write(JSON.stringify(data));
            }
            return res.end();
          }, delayTime);
        })();
    }
  }).listen(1112);

  console.log('server running on port 1112');

}).call(this);

//# sourceMappingURL=getheadusehttp.js.map
